// tests/example231.spec.ts
import { expect } from 'chai'
import { example231 } from '../src/example231'

console.log(`Fundamental(ES6)-Part-I
81. Create Keys with Function for Object

Write a JavaScript program to create an object with keys generated by running the provided function for each key.
The object will have the same values as the provided object.

 - Use Object.keys() to iterate over the object's keys.
 - Use Array.prototype.reduce() to create a new object with the same values and mapped keys using fn.

`)

describe('#example231', () => {
    it(`Input arguments are { a: 1, b: 2 }, (val, key) => key + val #1`, () => {
        expect(example231({ a: 1, b: 2 }, (val: any, key: any) => key + val)).deep.equal({ 'a1': 1, 'b2': 2 })
    })
})
