// src/example234.ts

// Create an object with the same keys as the provided object.
// It will also generate values generated by running the provided function for each value.
export function example234(inputObject: any, inputFunction: any): any {
    return Object.fromEntries(Object.keys(inputObject).map((key: any) => [key, inputFunction(inputObject[key])]))
}

